name: 'release'

on:
  push:
    tags:
      - "v*"
    branches:
      - "master"

jobs:
  build:
    name: pre-release
    runs-on: ubuntu-24.04

    steps:
      - name: checkout
        uses: actions/checkout@v4.1.7

      - name: build
        run: |
          go build

      - name: pre-release
        uses: softprops/action-gh-release@v2.0.5
        with:
          tag_name: master
          prerelease: true
          name: master
          files: |
            go-echo-example

      - name: tagged-release
        uses: softprops/action-gh-release@v2.0.5
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            go-echo-example
