name: 'release'

on:
  push:
    tags:
      - "v*"
    branches: master

jobs:
  build:
    name: pre-release
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4

      - name: build
        run: |
          go build

      - name: pre-release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: master
          prerelease: true
          title: master
          files: |
            go-echo-example

      - name: tagged-release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            go-echo-example
